services:
  nodelink:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodelink
    ports:
      - "2333:2333"
    environment:
      # --- Server Configuration ---
      NODELINK_SERVER_HOST: "0.0.0.0"
      NODELINK_SERVER_PORT: "2333"
    volumes:
    #   - ./local-music:/app/local-music
      - ./logs:/app/logs
      - ./.cache:/app/.cache
      - ./config.js:/app/config.js
    restart: unless-stopped