version: '3.8'

services:
  nodelink:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodelink
    ports:
      - "3000:3000"
    volumes:
    #   - ./local-music:/app/local-music
      - ./logs:/app/logs
      - ./.cache:/app/.cache
      - ./config.js:/app/config.js
    restart: unless-stopped
    networks:
      - bot_shared_net 
networks:
  bot_shared_net:
    external: true
    name: bot_network